### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xinhuaxi0510** [vferat/pycrostates#104]
Do you have any code to extract microstatal characteristics? For example, the average duration, time coverage, and the number of occurrences per second, thank you

**Comment by mscheltienne** [comment]
Hello,

Please have a look at the online documentation: https://pycrostates.readthedocs.io/en/latest/
You are probably referring to the [`compute_parameters`](https://pycrostates.readthedocs.io/en/latest/api/generated/pycrostates.segmentation.RawSegmentation.html#pycrostates.segmentation.RawSegmentation.compute_parameters) method from a Segmentation.

You can find an example using this method in this [tutorial](https://pycrostates.readthedocs.io/en/latest/generated/auto_tutorials/segmentation/00_segmentation.html#sphx-glr-generated-auto-tutorials-segmentation-00-segmentation-py).

Mathieu
