### ISSUE TITLE
`plot_raw_segmentation` has not a `show` parameter

### ISSUE THREAD

**Issue by vferat** [vferat/pycrostates#126]
`plot_raw_segmentation` has not a `show` parameter 

https://github.com/vferat/pycrostates/blob/588c644eab08c83cd4a1a67b2e01f7adf475aee0/pycrostates/viz/segmentation.py#L100

**Comment by mscheltienne** [comment]
It does, but probably not in the smartest way. It's part of `kwargs`. See:

https://github.com/vferat/pycrostates/blob/588c644eab08c83cd4a1a67b2e01f7adf475aee0/pycrostates/viz/segmentation.py#L84

And:

https://github.com/vferat/pycrostates/blob/588c644eab08c83cd4a1a67b2e01f7adf475aee0/pycrostates/viz/segmentation.py#L239-L245
