### ISSUE TITLE
segbase.compute_transition_matrix()

### ISSUE THREAD

**Issue by Mattlab-hub** [vferat/pycrostates#133]
Hi, 
I am trying to run:  
T_observed = segmentation.compute_transition_matrix() 

But I end up getting this error:
AttributeError: 'EpochsSegmentation' object has no attribute 'compute_transition_matrix'

Is this function not actively useable yet, or is there something else I need to do the get the segmentation to run this?

Best,
Matt

**Comment by mscheltienne** [comment]
Can you make sure you are using the latest version of `pycrostates`? This method was added recently.

Mathieu

**Comment by Mattlab-hub** [comment]
Ahh, yes, I didn't realize there was such a recent update. Yes, it does work now. Thank you!
