### ISSUE TITLE
Add pycrostates to the mne-installers

### ISSUE THREAD

**Issue by mscheltienne** [vferat/pycrostates#50]
Hey @hoechenberger, would you be interested in adding this library to the `mne-installers`?
It's a microstate analysis lib based around MNE, similar to `mne-microstates` with more functionalities, more tutorials, and better error-checking/error messages to guide the users.

It's tested against `mne-main` and it's available on conda-forge with req. similar to MNE.

**Comment by hoechenberger** [comment]
Hey, sure, feel free to make a PR; the changes need to go into https://github.com/mne-tools/mne-installers/blob/main/recipes/mne-python_1.1/construct.yaml
