### ISSUE TITLE
[JOSS Review] General Checks 

### ISSUE THREAD

**Issue by anshu-97** [vferat/pycrostates#62]
As part of #61

At present, the readme on the GitHub repository seems fairly vague with just a one-line summary of the software and links to documentation and installation instructions. While I understand that a [readme](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) should ideally be brief and concise, in my opinion, it should still convey the purpose and provide a brief overview of the software and its features in order to help potential new users get started. With that in mind, it may perhaps be helpful to include a few more lines about the purpose of microstate analysis and what it is typically used for. Although this may seem like a minor issue, having a more comprehensive readme could greatly facilitate potential new users in the onboarding process 😊

**Comment by mscheltienne** [comment]
Thanks for the review!

IMO, a `readme` should be detailed and should help users get started when a documentation build/website is not available. I prefer to point users towards the website if it exists (with a link in the `readme`, with a link in the top-right corner of the github-page) which is more detailed and easier to navigate. The 2 reasons are:
- better documentation
- maintenance

For the second point, what I mean is that example code snippets in the `readme`, e.g. as what you have for `NeuroKit2`, is a duplicate of examples on the website. Thus, any change to the code-base will require the maintainer to update the same information in 2 locations: the documentation website and the `readme`. Moreover, the documentation website is 'tested' and a change to the code-base which breaks an example will raise an alarm on a CI. This is not the case for the code-snippet in the `readme` (I don't have any knowledge of a CI/Workflow to test code in the `readme`).

----------------

Overall, -1 for this change.

**Comment by mscheltienne** [comment]
Our `readme` is closer to the format of `mne-python` or `scikit-learn` which points to the documentation.

**Comment by anshu-97** [comment]
Ok looks good to me!
