### ISSUE TITLE
ADD preprocessed raw dataset

### ISSUE THREAD

**Issue by vferat** [vferat/pycrostates#8]
For tutorials and new users, it would be interesting to have a fetcher for a dataset composed of several preprocessed EEG files 
For example: https://ftp.gwdg.de/pub/misc/MPI-Leipzig_Mind-Brain-Body-LEMON/EEG_MPILMBB_LEMON/

**Comment by mscheltienne** [comment]
We could use this simple one: https://github.com/bsl-tools/bsl/blob/main/bsl/datasets/_fetching.py
Not great, not terrible.
