### ISSUE TITLE
[Release] Release version 0.2.0

### ISSUE THREAD

**Issue by mscheltienne** [vferat/pycrostates#85]
@vferat As we changed quite a lot of stuff, among which the channel selection, I think it would be good to cut a new release. Also, it would be good to bump the minimum requirement to this new 0.2.0 release in the `mne-installers`: https://github.com/mne-tools/mne-installers/blob/59b276dba60e7ab7e76a8dcbbb581601b3fbd58f/recipes/mne-python_1.1/construct.yaml#L108

(⚠️ the link above is for the version 1.1 of MNE). MNE will release version 1.2 very soon (https://github.com/mne-tools/mne-python/milestone/23), so ideally, we cut a new release right before and bump the requirement in the `construct.yaml` of version 1.2.

For the JOSS review process, after the reviewers have closed their issues, the editor might ask for further changes. And finally, we will have to cut a new release for the JOSS review. So if this process is fast enough, we can cut a single new release; but if it's too slow, then I think it would be still good to cut a new release right before MNE 1.2 is out.

Let me know what you think.

**Comment by vferat** [comment]
I agree with you that the new channel selection should quickly be released. Do you have any idea of when MNE will release the  version ? I might be a matter of day, and we will surely not be done with the review process at this point.  In my opinion, we should make a release now and another one later,  with the editor/reviewers updates (+ additional features we might implement will wait for the answers).

**Comment by mscheltienne** [comment]
For MNE, I'm guessing 2 weeks. But we can indeed to it this way and release now.

**Comment by mscheltienne** [comment]
I'll keep this issue open until MNE releases 1.2, let's keep an eye on https://github.com/mne-tools/mne-installers and let's bump the minimum version as soon as the constructor for 1.2 is available (it's usually created couple days/1 week before the release).

**Comment by mscheltienne** [comment]
Closing as Eric Larson already bumped the version in the PR to prepare for 1.2.
